<a href="https://colab.research.google.com/github/Ramyanee/Ramyanee-DeepLearning.AI-TensorFlow-Developer-Professional-Certificate/blob/main/course1/housing_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
x = np.array([1,2,3,4,5,6])
y = np.array([100, 150, 200, 250, 300, 350]) # in thousand dollars


In [ ]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer = 'sgd', loss='mean_squared_error')
model.fit(x,y, epochs=100)
model.predict([7,8])

Epoch 1/100
1/1 [==============================] - 0s 447ms/step - loss: 54863.2031
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 25529.7129
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 11952.2969
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 5667.2656
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 2757.3772
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 1409.6139
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 784.8566
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 494.7357
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 359.5010
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 295.9594
Epoch 11/100
1/1 [==============================] - 0s 3ms/step - loss: 265.6066
Epoch 12/100
1/1 [==============================] - 0s 3ms/step - loss: 250.6212
Epoch 13/100
1/1 [=======

array([[416.17197],
       [472.12015]], dtype=float32)

In [ ]:
model.fit(x,y,epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 3ms/step - loss: 124.7865
Epoch 2/300
1/1 [==============================] - 0s 3ms/step - loss: 123.8774
Epoch 3/300
1/1 [==============================] - 0s 6ms/step - loss: 122.9749
Epoch 4/300
1/1 [==============================] - 0s 4ms/step - loss: 122.0789
Epoch 5/300
1/1 [==============================] - 0s 4ms/step - loss: 121.1895
Epoch 6/300
1/1 [==============================] - 0s 4ms/step - loss: 120.3067
Epoch 7/300
1/1 [==============================] - 0s 8ms/step - loss: 119.4302
Epoch 8/300
1/1 [==============================] - 0s 10ms/step - loss: 118.5600
Epoch 9/300
1/1 [==============================] - 0s 9ms/step - loss: 117.6963
Epoch 10/300
1/1 [==============================] - 0s 4ms/step - loss: 116.8389
Epoch 11/300
1/1 [==============================] - 0s 3ms/step - loss: 115.9874
Epoch 12/300
1/1 [==============================] - 0s 4ms/step - loss: 115.1425
Epoch 13/300
1/1 [==================

In [ ]:
model.predict([7,8])

array([[405.40024],
       [457.3865 ]], dtype=float32)

In [ ]:
model.fit(x,y,epochs=1000)


Epoch 1/1000
1/1 [==============================] - 0s 4ms/step - loss: 13.9145
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 13.8132
Epoch 3/1000
1/1 [==============================] - 0s 4ms/step - loss: 13.7125
Epoch 4/1000
1/1 [==============================] - 0s 9ms/step - loss: 13.6126
Epoch 5/1000
1/1 [==============================] - 0s 5ms/step - loss: 13.5134
Epoch 6/1000
1/1 [==============================] - 0s 5ms/step - loss: 13.4150
Epoch 7/1000
1/1 [==============================] - 0s 4ms/step - loss: 13.3173
Epoch 8/1000
1/1 [==============================] - 0s 6ms/step - loss: 13.2203
Epoch 9/1000
1/1 [==============================] - 0s 5ms/step - loss: 13.1239
Epoch 10/1000
1/1 [==============================] - 0s 5ms/step - loss: 13.0283
Epoch 11/1000
1/1 [==============================] - 0s 5ms/step - loss: 12.9334
Epoch 12/1000
1/1 [==============================] - 0s 3ms/step - loss: 12.8392
Epoch 13/1000
1/1 [==================

In [ ]:
model.predict([7,8])

array([[400.13953],
       [450.19083]], dtype=float32)